(function(){
var M=document.getElementById('ndaModal');if(!M)return;
var F=document.getElementById('ndaForm'),doc=document.getElementById('ndaDoc'),err=document.getElementById('ndaErr');
var MO=['January','February','March','April','May','June','July','August','September','October','November','December'];
var now=new Date(),DATE=MO[now.getMonth()]+' '+now.getDate()+', '+now.getFullYear();
function esc(s){return String(s).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function v(n,ph){var x=F[n].value.trim();return x?'<span class="nf ok">'+esc(x)+'</span>':'<span class="nf">'+ph+'</span>'}
function text(){return ''+
'<div class="nd-h"><b>WHATEVER TECH, LLC</b><br>848 Brickell Ave, Ste 950<br>Miami, FL</div>'+
'<h4>Confidentiality Agreement</h4><div class="nd-sub">Evaluation and Demonstration</div>'+
'<p>This Confidentiality Agreement (the “Agreement”) is dated '+DATE+', and is entered into by and between '+v('company','[Company legal name]')+', a '+v('etype','[entity type, e.g. Delaware corporation]')+' with its principal address at '+v('addr','[business address]')+' (the “Disclosing Party”), and WHATEVER TECH, LLC, a Florida limited liability company with its address at 848 Brickell Ave, Ste 950, Miami, FL (the “Receiving Party”).</p>'+
'<p>WHEREAS, the Disclosing Party is evaluating whether to engage the Receiving Party and, for that evaluation, wishes to share certain Confidential Information (as defined below) relating to its business processes and operations;</p>'+
'<p>WHEREAS, the Receiving Party is willing to receive such Confidential Information for the limited purpose (the “Purpose”) of preparing, designing and presenting a non-binding demonstration, prototype or proposal for the Disclosing Party (the “Demonstration”);</p>'+
'<p>WHEREAS, the parties wish such Confidential Information to be kept confidential;</p>'+
'<p>NOW, THEREFORE, in consideration of the mutual covenants set forth herein, and other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, the parties agree as follows:</p>'+
'<p><b>1. Confidential Information.</b> “Confidential Information” means any and all information relating to the Disclosing Party, its affiliates, its employees or any of their respective business operations, disclosed by or on behalf of the Disclosing Party to the Receiving Party in connection with the Purpose, including without limitation process descriptions, workflows, pricing, customer and supplier data, spreadsheets, files, exports, screen recordings, credentials and system access.</p>'+
'<p><b>2. Obligations.</b> Subject to Section 3 below, the Receiving Party shall treat all Confidential Information as confidential and, specifically, shall:</p>'+
'<p class="ind">(a) not use the Confidential Information for any purpose other than the Purpose;<br>(b) not disclose the Confidential Information to any third party without the Disclosing Party’s prior written consent, except to the Receiving Party’s Representatives (as defined below) in accordance with Section 2(e);<br>(c) not make copies of the Confidential Information, except as necessary to accomplish the Purpose;<br>(d) protect the Confidential Information with at least the same degree of care it applies to its own confidential information and, in no event, less than a reasonable degree of care; and<br>(e) limit dissemination of the Confidential Information to those directors, officers, members, employees, agents, subcontractors and professional advisors (collectively, “Representatives”) of the Receiving Party who have a need to know it, it being understood that the Receiving Party will inform all Representatives of the confidentiality obligations of this Agreement at the time of disclosure and will remain responsible for any breach by its Representatives.</p>'+
'<p><b>3. Exceptions.</b> The obligations in Section 2 shall not apply to information that:</p>'+
'<p class="ind">(a) is or becomes publicly available through no fault of the Receiving Party or its Representatives; or<br>(b) is lawfully disclosed to the Receiving Party by a third party without an obligation of confidentiality, but only to the extent such third party is lawfully permitted to do so; or<br>(c) was in the Receiving Party’s unrestricted possession prior to its disclosure; or<br>(d) is independently developed by the Receiving Party without use of or reference to the Confidential Information; or<br>(e) the Receiving Party is required to disclose (by deposition, interrogatory, request for documents, subpoena, civil investigative demand or similar process), provided that the Receiving Party shall (to the extent legally permitted) promptly notify the Disclosing Party of such requirement so that it may seek a protective order or other appropriate remedy, and shall furnish only that portion of the Confidential Information that, on the advice of its counsel, it is legally required to disclose.</p>'+
'<p><b>4. Term.</b> The Receiving Party’s obligations under Section 2 with respect to the Confidential Information, or any portion of it, shall continue until the earlier of three (3) years from the date of this Agreement or the date on which any exception in Section 3 becomes applicable to that portion of the Confidential Information.</p>'+
'<p><b>5. Ownership of Confidential Information.</b> The Receiving Party acknowledges that all Confidential Information is the sole property of the Disclosing Party, and the Receiving Party shall have no right to use it except as specifically provided in this Agreement. This Agreement grants no license or right of any kind, whether by implication, estoppel or otherwise.</p>'+
'<p><b>6. Ownership of the Demonstration.</b> The Demonstration, together with all software, source code, configurations, board structures, automations, templates, methodologies, know-how and materials created or used by the Receiving Party to prepare it, is and shall remain the sole property of the Receiving Party. Nothing in this Agreement transfers any right, title or interest in the Demonstration to the Disclosing Party, and the Disclosing Party shall not copy, reproduce, reverse engineer or create derivative works of the Demonstration. Any transfer of ownership or license of the Demonstration requires a separate written agreement between the parties.</p>'+
'<p><b>7. No Obligation to Contract.</b> This Agreement relates solely to the evaluation described in the Purpose. Nothing in this Agreement obligates either party to enter into any further agreement, to engage or provide any services, or to continue discussions, and nothing herein creates any exclusivity, partnership, joint venture, agency or employment relationship between the parties. Either party may end discussions at any time, for any reason and without liability, with the confidentiality obligations herein surviving.</p>'+
'<p><b>8. Return or Destruction.</b> Upon the Disclosing Party’s request, or promptly after the parties cease discussions without entering into a further agreement, the Receiving Party shall return all copies of the Confidential Information to the Disclosing Party or, at the Disclosing Party’s option, certify in writing that all such Confidential Information has been destroyed. The Receiving Party may retain copies it is required to keep by law or that remain stored in routine automatic backups, which shall remain subject to this Agreement for as long as they are retained.</p>'+
'<p><b>9. Entire Agreement; Amendment.</b> This Agreement constitutes the entire and fully integrated agreement and understanding of the parties with respect to confidentiality and ownership of information. It may be amended only by a subsequent written agreement between the parties.</p>'+
'<p><b>10. Counterparts; Electronic Signatures.</b> This Agreement may be executed in counterparts. It shall be binding and in full force and effect once both parties have signed and dated a counterpart and a copy of such signed counterpart has been delivered to the other party or its legal representative. Signature and delivery by email or other electronic means, including electronic signatures under the U.S. ESIGN Act and the Florida Uniform Electronic Transaction Act, shall be sufficient.</p>'+
'<p><b>11. Governing Law; Jurisdiction.</b> This Agreement shall be governed by the laws of the State of Florida, without regard to its conflict of laws principles. Any action arising in connection with this Agreement shall be brought in the federal or state courts located in Miami-Dade County, Florida, and the parties irrevocably consent to the jurisdiction of such courts.</p>'+
'<p><b>12. WAIVER OF JURY TRIAL.</b> IN ANY ACTION, PROCEEDING OR COUNTERCLAIM ARISING HEREUNDER, THE DISCLOSING PARTY AND THE RECEIVING PARTY, IN THE INTEREST OF SAVING TIME AND EXPENSE, HEREBY CONSENT TO TRIAL WITHOUT A JURY.</p>'+
'<p>IN WITNESS WHEREOF, each party has caused this Agreement to be duly executed on its behalf as of the date set forth below.</p>'+
'<div class="nd-sig"><div><div class="nd-k">Disclosing Party</div><div class="nd-line">'+(sig?'<img src="'+sig+'" alt="Signature">':'')+'</div>By: '+v('sname','[Full name]')+'<br>Title: '+v('stitle','[Title]')+'<br>Company: '+v('company','[Company legal name]')+'<br>Date: '+DATE+'</div>'+
'<div><div class="nd-k">Whatever Tech, LLC</div><div class="nd-line nd-pend">Countersignature on receipt</div>By: Alejandro Panizo<br>Title: Managing Director<br>Date: '+DATE+'</div></div>';}
function draw(){doc.innerHTML=text();}
var sig='';
// signature: type or draw
var cv=document.getElementById('ndaPad'),cx=cv.getContext('2d'),typed=document.getElementById('ndaTyped'),mode='type',drew=false,down=false;
function sizePad(){var r=cv.getBoundingClientRect(),d=devicePixelRatio||1;cv.width=r.width*d;cv.height=r.height*d;cx.setTransform(d,0,0,d,0,0);cx.lineWidth=2.2;cx.lineCap='round';cx.lineJoin='round';cx.strokeStyle='#0d0d10';drew=false;}
function pt(e){var r=cv.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top]}
cv.addEventListener('pointerdown',function(e){down=true;cv.setPointerCapture(e.pointerId);var p=pt(e);cx.beginPath();cx.moveTo(p[0],p[1]);});
cv.addEventListener('pointermove',function(e){if(!down)return;var p=pt(e);cx.lineTo(p[0],p[1]);cx.stroke();drew=true;});
['pointerup','pointercancel'].forEach(function(t){cv.addEventListener(t,function(){if(down){down=false;makeSig();}})});
document.getElementById('ndaClear').addEventListener('click',function(){cx.clearRect(0,0,cv.width,cv.height);drew=false;makeSig();});
function typedSig(){var t=typed.value.trim();if(!t)return'';var c=document.createElement('canvas');c.width=900;c.height=180;var k=c.getContext('2d');k.fillStyle='#0d0d10';k.font='italic 600 76px "Brush Script MT","Segoe Script","Snell Roundhand",cursive';k.textBaseline='middle';k.fillText(t,20,95,860);return c.toDataURL('image/png');}
function makeSig(){sig=mode==='type'?typedSig():(drew?cv.toDataURL('image/png'):'');draw();}
document.querySelectorAll('[data-sm]').forEach(function(b){b.addEventListener('click',function(){mode=b.dataset.sm;document.querySelectorAll('[data-sm]').forEach(function(x){x.setAttribute('aria-pressed',x===b)});document.getElementById('ndaTypeW').hidden=mode!=='type';document.getElementById('ndaDrawW').hidden=mode!=='draw';if(mode==='draw')sizePad();makeSig();});});
typed.addEventListener('input',makeSig);
F.addEventListener('input',function(e){if(e.target!==typed)draw();if(e.target.name==='sname'&&!typed.dataset.touched){typed.value=e.target.value;makeSig();}});
typed.addEventListener('keydown',function(){typed.dataset.touched=1});
function open(){M.hidden=false;document.documentElement.style.overflow='hidden';draw();setTimeout(function(){F.company.focus()},50);}
function close(){M.hidden=true;document.documentElement.style.overflow='';}
document.querySelectorAll('[data-nda-open]').forEach(function(b){b.addEventListener('click',open)});
M.addEventListener('click',function(e){if(e.target.closest('[data-nda-close]'))close();});
addEventListener('keydown',function(e){if(e.key==='Escape'&&!M.hidden)close();});
F.addEventListener('submit',function(e){e.preventDefault();var req=['company','etype','addr','sname','stitle','semail'],miss=req.filter(function(n){return!F[n].value.trim()});
var emOk=/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(F.semail.value.trim());
if(miss.length||!emOk||!sig||!F.consent.checked){err.hidden=false;err.textContent=miss.length?'Please complete all fields.':!emOk?'Please enter a valid email.':!sig?'Please add your signature.':'Please confirm you agree to sign electronically.';return;}
err.hidden=true;
var rec={company:F.company.value.trim(),entity:F.etype.value.trim(),address:F.addr.value.trim(),signer:F.sname.value.trim(),title:F.stitle.value.trim(),email:F.semail.value.trim(),date:DATE,signedAt:new Date().toISOString(),signature:sig,agreementHTML:text(),userAgent:navigator.userAgent};
window.WT_NDA=rec;
/* TODO: POST rec to n8n/Zapier webhook → store signed NDA (PDF) + audit trail, countersign, email copy to signer */
document.getElementById('ndaBody').hidden=true;document.getElementById('ndaDone').hidden=false;
var st=document.getElementById('ndaStatus');if(st){st.hidden=false;st.querySelector('b').textContent=rec.company;}
var ob=document.getElementById('ndaOpen');if(ob)ob.hidden=true;});
document.getElementById('ndaPrint').addEventListener('click',function(){var w=window.open('','_blank');if(!w)return;w.document.write('<!DOCTYPE html><html><head><title>NDA · '+esc(window.WT_NDA.company)+' · Whatever Tech</title><style>body{font:14px/1.55 Georgia,serif;color:#111;max-width:720px;margin:40px auto;padding:0 24px}h4{font-size:20px;text-align:center;margin:24px 0 2px;text-transform:uppercase;letter-spacing:.05em}.nd-sub{text-align:center;margin-bottom:22px}.nd-h{text-align:center;font-size:12px;letter-spacing:.06em}.ind{padding-left:22px}.nd-sig{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-top:30px}.nd-k{font-weight:700;text-transform:uppercase;font-size:12px;margin-bottom:8px}.nd-line{height:64px;border-bottom:1px solid #111;margin-bottom:8px;display:flex;align-items:flex-end}.nd-line img{max-height:60px;max-width:100%}.nd-pend{font-size:11px;color:#777}.audit{margin-top:36px;font:11px/1.5 monospace;color:#555;border-top:1px solid #ccc;padding-top:10px}</style></head><body>'+window.WT_NDA.agreementHTML+'<div class="audit">Electronically signed by '+esc(window.WT_NDA.signer)+' ('+esc(window.WT_NDA.email)+') on '+window.WT_NDA.signedAt+'</div><script>onload=function(){print()}<\/script></body></html>');w.document.close();});
})();
